### PR TITLE
Wc contact page

### PR DESCRIPTION
**Pull request by wocaldwell**
Added a html form for contacting us. No CSS styling.

### CODE REVIEW

**Comment by kayrahbear** [comment]
I see a form! 👍

**Comment by rueTH** [comment]
wowza

**Comment by wocaldwell** [comment]
Added css styling. Please review and let me know what you think.

**Comment by rueTH** [comment]
pretty

**Review by ghost — COMMENTED** [review]
pew pew

**Comment by kayrahbear** [comment]
woo! 👍

**Pull request merged**
