### PR TITLE
added nav css to main.css, added navbar to index.html

### PR DESCRIPTION
**Pull request by rueTH**

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
pew pew

**Comment by kayrahbear** [comment]
👍

**Comment by wocaldwell** [comment]
Looks good. Please add a link for the contact us page. Also the link to product.html should be products.html.

**Comment by rueTH** [comment]
Try it now

**Comment by kayrahbear** [comment]
perfect 👍

**Comment by wocaldwell** [comment]
👍

**Pull request merged**
